[package]
name = "pcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["fs", "sync", "io-util", "macros"] }
async-trait = "0.1.77"
regex = "1.10.3"
